CREATE SCHEMA IF NOT EXISTS rbh_bank;
SET SCHEMA rbh_bank;

-- =========================
-- CUSTOMER TABLE
-- =========================
CREATE TABLE customers (
    customer_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    full_name     VARCHAR(100) NOT NULL,
    email         VARCHAR(100) UNIQUE NOT NULL,
    pan_number    VARCHAR(10)  NOT NULL UNIQUE,
    mobile_number VARCHAR(15)  NOT NULL UNIQUE
);

-- =========================
-- ACCOUNT TABLE
-- =========================
CREATE TABLE accounts (
    account_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    account_number VARCHAR(20) UNIQUE NOT NULL,
    account_type   VARCHAR(20) NOT NULL,        -- SAVINGS / CURRENT / SALARY
    balance        DECIMAL(19,2) NOT NULL,
    status         VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    version        BIGINT,

    customer_id    BIGINT NOT NULL,

    CONSTRAINT fk_account_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id)
);

-- =========================
-- TRANSACTION TABLE
-- =========================
CREATE TABLE transactions (
    transaction_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    amount           DECIMAL(19,2) NOT NULL,
    type             VARCHAR(10) NOT NULL,      -- DEBIT / CREDIT
    transaction_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    utr               VARCHAR(50),
    remarks           VARCHAR(255),

    account_id       BIGINT NOT NULL,

    CONSTRAINT fk_tx_account
        FOREIGN KEY (account_id)
        REFERENCES accounts(account_id)
);
